#!/bin/bash
sudo yum update
sudo yum install -y apache2

cd /var/www/html

# Remove the default Apache index.html file
rm index.html

# Download your index.html file from GitHub
git clone https://github.com/bobbysstudies/EC2/blob/main/index.html

# Restart Apache to apply the changes
sudo service apache2 restart
